//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarWebApiServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int ID { get; set; }
        public int CarSize { get; set; }
        public string CarCompany { get; set; }
        public Nullable<int> CarColor { get; set; }
        public string Comments { get; set; }
    }
}
