//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarWebApiServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverLessonType
    {
        public int LessonType { get; set; }
        public string LessonTypeDriver { get; set; }
    }
}
