//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarWebApiServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Road
    {
        public int Id { get; set; }
        public string RoadName { get; set; }
        public int MaxSpeed { get; set; }
        public Nullable<int> NumLanes { get; set; }
        public string RoadDesc { get; set; }
        public short RoadNum { get; set; }
    }
}
